Repository BadDeathclaw/TG-Claw, pull requests merged in 2018-11, with the labels that each got.

#114 vault updates
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/generic/CentCom.dmm
  code/controllers/subsystem/research.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/turfs/simulated/floor/f13_floors.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/vault.dm
Labels: :earth_americas:Map Edit, Fix

#115 Adds 3 minute respawn timer + bypass for admins, refactors factions for jobs so it isn't horrible
  code/__DEFINES/mobs.dm
  code/controllers/subsystem/job.dm
  code/datums/components/thermite.dm
  code/game/turfs/simulated/floor/plating.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/den.dm
  code/modules/jobs/job_types/job.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/jobs/job_types/vault.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/reagent_containers/patch.dm
  config/config.txt
Labels: :eight_spoked_asterisk:Feature, Administation

#133 Rnd fix, or alternate title: fuck off bos
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/generic/CentCom.dmm
  code/controllers/subsystem/research.dm
  code/game/vault_door.dm
  code/modules/research/rdconsole.dm
  code/modules/research/server.dm
  code/modules/research/techweb/_techweb.dm
Labels: FUCK, Fix

#135 [literally gucci gang] RnD techweb rework
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/diseases/advance/symptoms/viral.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/cloning.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/mecha/mech_fabricator.dm
  code/game/objects/items/RCD.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/game/objects/items/devices/multitool.dm
  code/game/objects/items/dna_injector.dm
  code/game/objects/items/grenades/syndieminibomb.dm
  code/game/objects/items/robot/robot_parts.dm
  code/game/objects/items/tools/crowbar.dm
  code/game/objects/items/tools/screwdriver.dm
  code/game/objects/items/tools/weldingtool.dm
  code/game/objects/items/tools/wirecutters.dm
  code/game/objects/items/tools/wrench.dm
  code/game/vault_door.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/mining/machine_vending.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/boxes_magazines/external/shotgun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/pins.dm
  code/modules/reagents/chemistry/machinery/pandemic.dm
  code/modules/research/designs/comp_board_designs.dm
  code/modules/research/designs/equipment_designs.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/designs/mecha_designs.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/designs/power_designs.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/stock_parts.dm
  code/modules/research/techweb/_techweb_node.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/organs/augments_arms.dm
Labels: Balance/Rebalance, Feature

#142 fixes more access issues, also made sure vaulties cant buy a different shuttle
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/access.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/computer/crew.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/bos.dm
Labels: Fix, Map Edit

#143 [GUCCI] Expansion of techweb specific servers and configuration of servers for specific point generation, readds a forgotten thing for diseases and ORM tweak
  code/controllers/subsystem/research.dm
  code/datums/components/storage/concrete/bag_of_holding.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/modules/mining/machine_redemption.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  code/modules/research/machinery/_production.dm
  code/modules/research/rdconsole.dm
  code/modules/research/research_disk.dm
  code/modules/research/server.dm
  code/modules/research/techweb/__techweb_helpers.dm
  code/modules/research/techweb/_techweb.dm
Labels: Feature, Fix, optimization

#157 Adds legion support roles and QoL improvements
  _maps/map_files/BoxStation/BoxStation.dmm
  code/__DEFINES/jobs.dm
  code/game/machinery/computer/card.dm
  code/game/objects/effects/landmarks.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/jobs.dm
  code/modules/projectiles/gun.dm
  icons/mob/actions/actions_items.dmi
  icons/mob/mask.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/clothing/masks.dmi
Labels: Feature

#159 Checks for null mind when respawning
  code/modules/mob/mob.dm
Labels: FUCK, Feature, High, Ready for merge, Refractor, SCIENCE, bug, optimization

#167 Explorer suit buff
  code/modules/mining/equipment/explorer_gear.dm
Labels: Balance/Rebalance

#183 Threeee dawg auuu
  code/__DEFINES/admin.dm
  code/__DEFINES/preferences.dm
  code/__DEFINES/sound.dm
  code/_globalvars/bitfields.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/playsound.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggles.dm
  config/admin_ranks.txt
  config/jukebox_music/A Wonderful Guy+1320+5.ogg
  config/jukebox_music/Aint That A Kick+1440+5.ogg
  config/jukebox_music/Anything Goes+1880+5.ogg
  config/jukebox_music/Boogie Man+1620+5.ogg
  config/jukebox_music/Butcher Pete+1650+5.ogg
  config/jukebox_music/Civilization+2000+5.ogg
  config/jukebox_music/Crazy He Calls Me+2050+5.ogg
  config/jukebox_music/Easy Living+2010+5.ogg
  config/jukebox_music/Fox Boogie+2150+5.ogg
  config/jukebox_music/Happy Times+1850+5.ogg
  config/jukebox_music/Pistol Packin Mama+1630+5.ogg
  config/jukebox_music/Tickled Pink+1280+5.ogg
Labels: Administation, Feature

#170 config fix and stuff
  config/config.txt
  config/motd.txt
Labels: Administation

#198 Adds some glass icon states
  lewd/objects.dm
Labels: Feature

#196 Updates shockcollars
  code/game/objects/items/devices/radio/electropack.dm
Labels: Feature

#186 Veteran Decanus & Laser/Plasma weaponry rebalance
  _maps/map_files/BoxStation/BoxStation.dmm
  code/__DEFINES/jobs.dm
  code/game/machinery/computer/card.dm
  code/game/objects/effects/landmarks.dm
  code/modules/clothing/head/helmet.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/jobs.dm
  code/modules/projectiles/guns/energy/laser.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Balance/Rebalance, Feature

#209 Adds in basic rigsuit framework
  code/modules/clothing/clothing.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/research/machinery/_production.dm
  icons/mob/rig_back.dmi
  icons/mob/rig_modules.dmi
  icons/obj/rig_modules.dmi
  rigsuits/_READ THIS.dm
  rigsuits/modules/combat.dm
  rigsuits/modules/computer.dm
  rigsuits/modules/handheld.dm
  rigsuits/modules/modules.dm
  rigsuits/modules/ninja.dm
  rigsuits/modules/utility.dm
  rigsuits/modules/vision.dm
  rigsuits/rig.dm
  rigsuits/rig_armormod.dm
  rigsuits/rig_attackby.dm
  rigsuits/rig_pieces.dm
  rigsuits/rig_verbs.dm
  rigsuits/rig_wiring.dm
  rigsuits/rigicons.dmi
  rigsuits/suits/alien.dm
  rigsuits/suits/combat.dm
  rigsuits/suits/ert_suits.dm
  rigsuits/suits/light.dm
  rigsuits/suits/merc.dm
  rigsuits/suits/station.dm
  tgstation.dme
Labels: Feature

#203 No sorcery for legionnaires
  code/game/machinery/autolathe.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/mob/living/living.dm
  code/modules/projectiles/guns/misc/medbeam.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
Labels: Feature

#217 Invisible icon fix
  code/game/machinery/dance_machine.dm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/modules/clothing/head/collectable.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  lewd/_lewd.dm
  lewd/objects.dm
Labels: Fix

#204 Job exp system
  code/__DEFINES/preferences.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/den.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/jobs/job_types/vault.dm
  code/modules/jobs/jobs.dm
  config/config.txt
Labels: Administation, Feature

#232 [s] ports autolathe infinite metal/glass fix
  code/game/machinery/autolathe.dm
Labels: FUCK, Fix

#231 Memes
  code/__DEFINES/jobs.dm
  code/modules/jobs/job_types/wasteland.dm
Labels: Feature

#230 Nerfs Garborgs
  code/game/objects/items/mop.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Balance/Rebalance, Removal

#221 [WORK IN PROGRESS] Adds in a framework for hardsuits to become power cell eating power armor
  code/modules/clothing/spacesuits/hardsuit.dm
Labels: Feature

#228 Carp meat toxicity increase
  code/modules/food_and_drinks/food/snacks_meat.dm
Labels: Feature

#236 Updates healing powder
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Feature
