Repository BadDeathclaw/TG-Claw, pull requests merged in 2018-12, with the labels that each got.

#229 Lifegiver trait
  code/__DEFINES/traits.dm
  code/datums/traits/good.dm
Labels: Feature

#235 Butchering and masks
  code/__DEFINES/jobs.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/hostile/deathclaw.dm
  code/modules/mob/living/simple_animal/hostile/ghoul.dm
  code/modules/mob/living/simple_animal/hostile/wasteanimals.dm
Labels: Feature

#177 The Casino Update
  _maps/map_files/BoxStation/BoxStation.dmm
  code/datums/components/material_container.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/camera/camera_assembly.dm
  code/game/machinery/slotmachine.dm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/items/stacks/cash.dm
  code/game/objects/items/stacks/f13Cash.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/kitchen_spike.dm
  code/game/turfs/simulated/floor/f13_floors.dm
  code/modules/jobs/job_types/den.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/library/lib_items.dm
  code/modules/mining/mint.dm
  code/modules/mining/money_bag.dm
  icons/obj/cross.dmi
  icons/obj/economy.dmi
  icons/obj/f13misc.dmi
  icons/obj/fence.dmi
  icons/obj/storage.dmi
  icons/turf/f13floorsmisc.dmi
  sound/effects/crossed.ogg
  tgstation.dme
Labels: Feature, Map Edit

#222 Rigsuit cleanup
  code/modules/rigsuits/_READ THIS.dm
  code/modules/rigsuits/modules/combat.dm
  code/modules/rigsuits/modules/computer.dm
  code/modules/rigsuits/modules/handheld.dm
  code/modules/rigsuits/modules/modules.dm
  code/modules/rigsuits/modules/ninja.dm
  code/modules/rigsuits/modules/utility.dm
  code/modules/rigsuits/modules/vision.dm
  code/modules/rigsuits/rig.dm
  code/modules/rigsuits/rig_armormod.dm
  code/modules/rigsuits/rig_attackby.dm
  code/modules/rigsuits/rig_pieces.dm
  code/modules/rigsuits/rig_verbs.dm
  code/modules/rigsuits/rig_wiring.dm
  code/modules/rigsuits/rigicons.dmi
  code/modules/rigsuits/suits/alien.dm
  code/modules/rigsuits/suits/combat.dm
  code/modules/rigsuits/suits/ert_suits.dm
  code/modules/rigsuits/suits/light.dm
  code/modules/rigsuits/suits/merc.dm
  code/modules/rigsuits/suits/station.dm
  tgstation.dme
Labels: Refractor, optimization

#274 Travis Fix weird node errors
  .travis.yml
  tgui/build.sh
Labels: Administation, Fix

#244 Soap fix
  code/game/objects/items/clown_items.dm
Labels: Fix

#253 Iron Fist trait
  code/__DEFINES/traits.dm
  code/datums/traits/good.dm
Labels: Feature

#260 Nerfs shotguns
  code/modules/clothing/head/helmet.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/projectiles/ammunition/ballistic/shotgun.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: Balance/Rebalance

#263 Update BoxStation.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit

#272 vunerability fix
  tgui/package-lock.json
  tgui/package.json
Labels: Administation, Fix, High

#270 [gucci] Power armor expansion
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Do Not Merge, Feature

#292 Remove sensitive configs
  .gitignore
  config/admins.example.txt
  config/dbconfig.example.txt
Labels: Administation, High

#237 Fixes nonexistant icon of tiled desert
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor/f13_floors.dm
  code/game/turfs/simulated/floor/mineral_floor.dm
  code/game/turfs/simulated/floor/plasteel_floor.dm
Labels: Fix, optimization

#248 Solar panel fix
  code/modules/power/solar.dm
Labels: Fix

#281 Update fence.dm
  code/game/objects/structures/fence.dm
Labels: Fix

#291 sheriff and deputy badges
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/jobs/job_types/den.dm
  icons/mob/mob.dmi
  icons/mob/rig_back.dmi
  icons/obj/card.dmi
Labels: Feature

#279 Adds LOOC
  code/__DEFINES/admin.dm
  code/__DEFINES/logging.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/preferences.dm
  code/__DEFINES/say.dm
  code/__HELPERS/_logging.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/configuration.dm
  code/_globalvars/logging.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/input.dm
  code/controllers/subsystem/ticker.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/individual_logging.dm
  code/modules/client/player_details.dm
  code/modules/client/preferences_toggles.dm
  code/modules/client/verbs/looc.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/mob/mob_defines.dm
  config/config.txt
  config/game_options.txt
  interface/stylesheet.dm
  tgstation.dme
Labels: Feature

#296 Iron_Fist_Fix
  code/datums/traits/good.dm
Labels: Balance/Rebalance

#294 erp href fixes
  interactions/_interaction.dm
  interactions/interaction_interface.dm
  lewd/_lewd.dm
  lewd/lewd_datums.dm
  lewd/lewd_interactions.dm
Labels: Fix, optimization

#290 Big_Leagues_Perk
  code/__DEFINES/traits.dm
  code/_onclick/item_attack.dm
  code/datums/traits/good.dm
Labels: Feature

#298 Fixes purple icons (again)
  code/game/turfs/simulated/floor.dm
Labels: Fix

#289 Changes number of job slots
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
Labels: Feature

#286 Mutagen to FEV
  _maps/RandomRuins/LavaRuins/lavaland_surface_seed_vault.dmm
  _maps/RandomRuins/SpaceRuins/abandonedzoo.dmm
  _maps/RandomRuins/SpaceRuins/gasthelizards.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/objects/items/grenades/chem_grenade.dm
  code/game/objects/items/tanks/watertank.dm
  code/modules/cargo/packs.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/chemistry/recipes/toxins.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/research/designs/weapon_designs.dm
  strings/tips.txt
Labels: Feature

#284 bilboard fix and mapping spawner icon states, also enables the job time thingy
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/generic/CentCom.dmm
  code/controllers/subsystem/research.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/objects/effects/F13bilboards.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/turfs/closed.dm
  code/game/turfs/simulated/floor/f13_floors.dm
  code/modules/awaymissions/super_secret_room.dm
  config/config.txt
  lewd/_lewd.dm
  lewd/lewd_species.dm
  lewd/objects.dm
Labels: Balance/Rebalance, Fix, optimization

#297 Adds locks to fence doors
  code/game/machinery/doors/door.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/mineral_doors.dm
Labels: Feature

#293 Update observer.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#314 shh
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/den.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/jobs/job_types/vault.dm
Labels: Administation, FUCK, Fix

#309 ports pits
  code/game/turfs/simulated/floor/f13_floors.dm
  code/game/turfs/turf.dm
  code/modules/pits/pits.dm
  icons/misc/Pit.dmi
  tgstation.dme
Labels: Feature

#313 Update reagent_containers.dm
  code/modules/reagents/reagent_containers.dm
Labels: Administation, Removal

#308 Update sprite_accessories.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
Labels: optimization

#299 Fix for loot spawning outside of closets, crates
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Fix

#300 Rangemaster & Remington ammo intercompatibility
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/boxes_magazines/internal/rifle.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/research/designs/autolathe_designs.dm
Labels: Feature

#301 Slot machine payout fix
  code/game/machinery/slotmachine.dm
Labels: Fix

#302 updates travis
  tools/travis/build_byond.sh
Labels: Administation
