Repository BadDeathclaw/TG-Claw, pull requests merged in 2019-04, with the labels that each got.

#736 Alright it's fixed
  code/game/machinery/deployable.dm
Labels: Bugfix [No Hold]

#747 makes streetlight **actually** work
  code/game/area/Space_Station_13_areas.dm
  code/modules/power/lighting.dm
Labels: Bugfix [No Hold]

#748 Removes References to Disney's Star Wars™ Franchise
  code/modules/mapping/map_template.dm
Labels: Copy Change [No Hold]

#749 re-ads erp so admins can escalate you when you slap someone's ass
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  interactions/lewd/_lewd.dm
  interactions/lewd/lewd_datums.dm
  interactions/lewd/lewd_interactions.dm
  interactions/lewd/lewd_species.dm
  interactions/lewd/objects.dm
  tgstation.dme
Labels: FUCK, Work In Progress [DNM]

#742 Adds variety of weapons to wastelanders
  code/modules/jobs/job_types/wasteland.dm
Labels: Feature [24hr Hold], Quality of Life

#750 Config fix and smooths out animation between tiles
  code/game/atoms_movable.dm
  config/config.txt
Labels: Bugfix [No Hold], Quality of Life

#752 mystery patch
  code/datums/datumvars.dm
  code/game/machinery/newscaster.dm
Labels: Bugfix [No Hold]

#744 Minor Tweaks and Fixes
  _maps/map_files/BoxStation/BoxStation.dmm
  code/__DEFINES/lighting.dm
  code/__DEFINES/tools.dm
  code/game/machinery/_machinery.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/powerfist.dm
  code/game/objects/items/shields.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/twohanded.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/head/helmet.dm
  code/modules/crafting/craft.dm
  code/modules/crafting/guncrafting.dm
  code/modules/crafting/recipes.dm
  code/modules/jobs/job_types/den.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/research/designs/autolathe_designs.dm
Labels: Balance [24hr Hold], Feature [24hr Hold], Quality of Life

#720 RnD Weapon Changes
  code/modules/projectiles/ammunition/energy/gravity.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Balance [24hr Hold]

#746 Adds New Interface / Other minor changes
  code/controllers/subsystem/shuttle.dm
  config/config.txt
  icons/deathclawlogo.png
  interface/interface.dm
  interface/skin.dmf
Labels: Feature [24hr Hold], Quality of Life

#788 timers unable to go to -1
  code/controllers/subsystem/timer.dm
Labels: Bugfix [No Hold], FUCK

#783 Unfucks FPS
  config/config.txt
Labels: Bugfix [No Hold]

#773 AMR v2
  code/modules/jobs/job_types/ncr.dm
  code/modules/projectiles/boxes_magazines/internal/rifle.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/research/designs/autolathe_designs.dm
Labels: Balance [24hr Hold]

#789 Glide size = 8
  code/game/atoms_movable.dm
Labels: Bugfix [No Hold], FUCK

#772 Bolas
  code/game/objects/items/handcuffs.dm
  code/modules/jobs/job_types/legion.dm
Labels: Balance [24hr Hold]

#785 Plasma
  code/modules/mob/living/simple_animal/hostile/wastebots.dm
  code/modules/projectiles/guns/energy/laser.dm
Labels: Balance [Suggestion]

#778 Armor re-balance
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
Labels: Balance [24hr Hold], No Hold [Ren Override]

#792 removes vunerability shit
  tgui/package.json
Labels: Bugfix [No Hold]

#770 Adds Cowboy Repeaters and Brush Guns
  code/modules/jobs/job_types/ncr.dm
  code/modules/projectiles/boxes_magazines/internal/shotgun.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  icons/obj/guns/projectile.dmi
  sound/f13weapons/brushgunfire.ogg
  sound/f13weapons/cowboyrepeaterfire.ogg
  sound/f13weapons/cowboyrepeaterreload.ogg
Labels: Feature [24hr Hold], Hold[Ren input needed], Sprites

#796 Minor Bugfixes
  code/datums/traits/negative.dm
  code/modules/jobs/jobs.dm
Labels: Bugfix [No Hold]

#809 Minor Bugfixes 2.0
  code/modules/jobs/jobs.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Labels: Bugfix [No Hold]

#801 Update ticker.dm
  code/controllers/subsystem/ticker.dm
Labels: Bugfix [No Hold]

#813 Lets fix that gap eh
  interface/skin.dmf
Labels: Bugfix [No Hold]

#832 unfucks travis: webedit edition
  .travis.yml
  code/__DEFINES/rust_g.dm
  code/datums/helper_datums/getrev.dm
  code/game/world.dm
  rust_g.dll
  tools/travis/build_dependencies.sh
Labels: Bugfix [No Hold], FUCK

#819 fixes the dumb UI
  interface/skin.dmf
Labels: Bugfix [No Hold]

#823 changes two capitaliziations
  code/modules/clothing/under/f13.dm
Labels: Bugfix [No Hold]

#814 BOS access fix
  code/modules/jobs/job_types/bos.dm
Labels: Bugfix [No Hold]

#816 Bible Tweak
  code/game/objects/items/storage/book.dm
Labels: Balance [24hr Hold]

#817 Adds cover to dense objects
  code/game/machinery/_machinery.dm
  code/game/machinery/computer/_computer.dm
  code/game/machinery/constructable_frame.dm
  code/game/machinery/deployable.dm
  code/game/objects/structures.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/girders.dm
Labels: Do Not Merge, Feature [24hr Hold]

#840 tempfix faction deaths
  code/datums/mood_events/generic_negative_events.dm
Labels: Bugfix [No Hold]

#829 Adds Tribadism.
  interactions/lewd/_lewd.dm
  interactions/lewd/lewd_datums.dm
Labels: Feature [24hr Hold]

#837 de-runtimes roundstart zoomables
  code/modules/projectiles/gun.dm
Labels: Bugfix [No Hold]

#841 Adds six new posters
  code/game/objects/effects/contraband.dm
  icons/obj/contraband.dmi
Labels: Feature [24hr Hold]

#842 moves all technopreak shit to a trait
  code/__DEFINES/traits.dm
  code/datums/mind.dm
  code/datums/traits/good.dm
  code/game/objects/objs.dm
  code/modules/clothing/suits/armor.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/enclave.dm
  code/modules/jobs/job_types/silicon.dm
  code/modules/jobs/job_types/vault.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/research/rdconsole.dm
Labels: Feature [24hr Hold]

#795 Adds several sound effects
  code/datums/components/storage/storage.dm
  code/game/machinery/deployable.dm
  code/game/objects/items/devices/flashlight.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/wasteanimals.dm
  sound/creatures/cazador_buzz.ogg
  sound/creatures/radroach_attack.ogg
  sound/creatures/radroach_chitter.ogg
  sound/creatures/radscorpion_attack.ogg
  sound/creatures/radscorpion_snip.ogg
  sound/effects/flare_light.ogg
  sound/effects/knife_draw.ogg
  sound/effects/sandbag_build.ogg
  sound/effects/torch_light.ogg
Labels: Feature [24hr Hold], Quality of Life

#831 Stimpak and Healing Powder Change Proposal
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Balance [24hr Hold], Balance [Suggestion]

#833 Sawn Off Weapons
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  icons/obj/guns/projectile.dmi
Labels: Feature [24hr Hold]

#845 Minor Tweaks and Fixes 2
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/unpowered.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/structures/mineral_doors.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/den.dm
  code/modules/mob/living/simple_animal/hostile/raider.dm
  code/modules/projectiles/boxes_magazines/internal/shotgun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/projectile/bullets/_incendiary.dm
  icons/mob/head.dmi
  icons/obj/guns/projectile.dmi
Labels: Balance [24hr Hold], Bugfix [No Hold]

#827 Modifies shooting delay (no more paralysis) and adds a throwing delay
  code/__DEFINES/status_effects.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/items.dm
  code/game/objects/items/weaponry.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/status_procs.dm
  code/modules/mob/status_procs.dm
  code/modules/projectiles/gun.dm
Labels: Feature [24hr Hold]

#828 Enclave Mountain Bunker V2.0
  _maps/map_files/BoxStation/BoxStation.dmm
  code/game/machinery/exp_cloner.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/structures/musician.dm
Labels: Feature [24hr Hold], Map Edit [Will Break Others]

#849 Standardizes cloning code
  code/game/machinery/exp_cloner.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/research/designs/machine_designs.dm
Labels: Feature [24hr Hold]

#851 Enclave Bunker v2.1
  _maps/map_files/BoxStation/BoxStation.dmm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/unpowered.dm
  code/game/objects/items/storage/book.dm
  code/modules/clothing/suits/armor.dm
Labels: Balance [24hr Hold], Feature [24hr Hold]

#869 Slight map audit
  _maps/map_files/BoxStation/BoxStation.dmm
  code/__HELPERS/unsorted.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/paperwork/fluff/experiments.dm
  tgstation.dme
Labels: Bugfix [No Hold], Feature [24hr Hold], Map Edit [Will Break Others]

#865 [READY] Makes Veteran Rangers look mildly better.
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/under/f13.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/projectiles/boxes_magazines/external/pistol.dm
  icons/mob/feet.dmi
  icons/mob/hands.dmi
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/suits.dmi
Labels: Feature [24hr Hold], Work In Progress [DNM]
