Repository BadDeathclaw/TG-Claw, pull requests merged in 2019-06, with the labels that each got.

#991 The Great Parhum Sewer System
  _maps/map_files/Pahrump/Pahrump.dmm
  code/game/objects/structures/ladders.dm
  icons/obj/structures.dmi
Labels: Feature [24hr Hold], Map Edit [Will Break Others]

#996 Revert "Revert "Revert "Outcasts merge"""
  _maps/_basemap.dm
Labels: Bugfix [No Hold], FUCK

#1075 Revert "Altered Map Pahrump"
  Pahrump.dmm
Labels: Bugfix [No Hold]
