Repository BadDeathclaw/TG-Claw, pull requests merged in 2019-07, with the labels that each got.

#1148 Hotfix [Invisible Ithacas]
  icons/obj/guns/projectile.dmi
Labels: Bugfix [No Hold]

#1150 Fixes donator save slots (HOTFIX)
  code/modules/client/preferences.dm
Labels: Bugfix [No Hold]

#1162 Spam prevention, Legion Prime Sprites, gun slowdown reduction
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/clothing/head/helmet.dm
  code/modules/crafting/forge.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Balance [24hr Hold]

#1168 Adds consent preferences
  code/__DEFINES/preferences.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggles.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/simple_animal/hostile/deathclaw/funclaw.dm
  interactions/_interaction.dm
  interactions/interaction_mob.dm
  interactions/lewd/_lewd.dm
  interactions/lewd/lewd_interactions.dm
Labels: Hold[Ren input needed]
