Repository BadDeathclaw/TG-Claw, pull requests merged in 2019-05, with the labels that each got.

#895 Travis buffs
  .dockerignore
  .gitignore
  .travis.yml
  Dockerfile
  dependencies.sh
  tgui/build.sh
  tgui/build_assets.bat
  tgui/install_dependencies.bat
  tgui/package-lock.json
  tools/deploy.sh
  tools/mapmerge2/dmm.py
  tools/mapmerge2/map_scripts/apc_pixel_offsets.txt
  tools/mapmerge2/precommit.py
  tools/mapmerge2/requirements.txt
  tools/mapmerge2/update_paths.py
  tools/travis/before_build_byond.sh
  tools/travis/build_byond.sh
  tools/travis/build_dependencies.sh
  tools/travis/build_tools.sh
  tools/travis/install_build_tools.sh
Labels: Bugfix [No Hold], Feature [24hr Hold]

#891 Fixes menu buttons
  config/config.txt
  interface/interface.dm
Labels: Bugfix [No Hold]

#892 Adds extra BoS secondary ammo
  code/modules/jobs/job_types/bos.dm
Labels: Balance [24hr Hold], Feature [24hr Hold]

#899 Bugfix time
  code/__DEFINES/is_helpers.dm
  code/game/objects/items/lock.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/turfs/simulated/floor/f13_floors.dm
  code/modules/jobs/job_types/job.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/energy.dm
  config/jukebox_music/sounds/A Wonderful Guy+1320+5.ogg
  config/jukebox_music/sounds/Aint That A Kick+1440+5.ogg
  config/jukebox_music/sounds/Anything Goes+1880+5.ogg
  config/jukebox_music/sounds/Boogie Man+1620+5.ogg
  config/jukebox_music/sounds/Butcher Pete+1650+5.ogg
  config/jukebox_music/sounds/Civilization+2000+5.ogg
  config/jukebox_music/sounds/Crazy He Calls Me+2050+5.ogg
  config/jukebox_music/sounds/Easy Living+2010+5.ogg
  config/jukebox_music/sounds/Fox Boogie+2150+5.ogg
  config/jukebox_music/sounds/Happy Times+1850+5.ogg
  config/jukebox_music/sounds/Pistol Packin Mama+1630+5.ogg
  config/jukebox_music/sounds/Tickled Pink+1280+5.ogg
Labels: Bugfix [No Hold]

#898 More healing items, plants
  code/game/objects/structures/flora.dm
  code/game/objects/structures/wasteplants.dm
  code/game/turfs/simulated/floor/f13_floors.dm
  code/modules/crafting/recipes.dm
  code/modules/hydroponics/grown/broc.dm
  code/modules/hydroponics/grown/feracactus.dm
  code/modules/hydroponics/grown/fungus.dm
  code/modules/hydroponics/grown/mutfruit.dm
  code/modules/hydroponics/grown/xander.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/patch.dm
  icons/obj/flora/deadtrees.dmi
  icons/obj/flora/wastelandflora.dmi
  icons/obj/hydroponics/growing_fruits.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
  tgstation.dme
Labels: Feature [24hr Hold]

#902 Updates recon rangers' uniforms' icons.
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#908 Funclaws
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/hostile/deathclaw.dm
  code/modules/mob/living/simple_animal/hostile/deathclaw/funclaw.dm
  honk/sound/interactions/clawcum1.ogg
  honk/sound/interactions/clawcum2.ogg
  interactions/_interaction.dm
  interactions/interaction_interface.dm
  interactions/interaction_mob.dm
  interactions/lewd/_lewd.dm
  interactions/lewd/lewd_datums.dm
  interactions/lewd/lewd_interactions.dm
  interactions/lewd/lewd_species.dm
  interactions/lewd/objects.dm
  tgstation.dme
Labels: FUCK, Feature [24hr Hold]

#910 Small RnD Energy Weapons Addition and Tweak
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature [24hr Hold]

#906 Misc changes: AI Laws + Recycled Stimpaks
  code/modules/crafting/recipes.dm
  config/silicon_laws.txt
Labels: Feature [24hr Hold]

#896 Drug opacity
  code/datums/mood_events/drug_events.dm
Labels: Feature [24hr Hold]

#911 [s] nerfs myself
  code/modules/integrated_electronics/subtypes/converters.dm
Labels: Administrative, Bugfix [No Hold]

#913 Makes barrel cactus irradiate slightly.
  code/modules/hydroponics/grown/feracactus.dm
Labels: Feature [24hr Hold]
