Repository BadDeathclaw/TG-Claw, pull requests merged in 2019-03, with the labels that each got.

#669 Blood cascade fix
  code/__DEFINES/misc.dm
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Bugfix [No Hold]

#666 Hotfixes cows
  code/controllers/subsystem/vote.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Labels: Bugfix [No Hold]

#665 Raider loot and some balance changes
  code/modules/mob/living/simple_animal/hostile/raider.dm
Labels: Balance [24hr Hold]

#681 Gecko fix
  code/game/objects/items/stacks/sheets/leather.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/mob/living/simple_animal/hostile/wasteanimals.dm
  icons/obj/stack_objects.dmi
Labels: Feature [24hr Hold]

#682 Some cleanup, disables MMB exploit
  code/_onclick/drag_drop.dm
  code/controllers/configuration/entries/general.dm
  code/game/machinery/autolathe.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  config/config.txt
Labels: Bugfix [No Hold]

#688 Fixes role configuration
  config/admin_ranks.txt
Labels: Bugfix [No Hold]

#680 Adds Vault 223 (Russian Vault) (Gulag's Electric Boongaloo 2)
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/generic/CentCom.dmm
Labels: Map Edit [Will Break Others]

#685 Fixes softcrit whispering
  code/modules/mob/living/living.dm
  code/modules/mob/living/say.dm
Labels: Bugfix [No Hold]

#691 Adds machete gladius
  code/game/objects/items/weaponry.dm
  icons/mob/inhands/weapons/melee_lefthand.dmi
  icons/mob/inhands/weapons/melee_righthand.dmi
  icons/obj/items_and_weapons.dmi
Labels: Feature [24hr Hold]

#697 adds better lock sprites / grammar
  code/game/objects/items/twohanded.dm
  icons/obj/lock.dmi
Labels: Feature [24hr Hold], Sprites

#701 adds battlecoat and enclave combat armor + sprites for t60 and chinese stealthsuit
  code/modules/clothing/suits/armor.dm
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/suits.dmi
Labels: Feature [24hr Hold]

#693 Not my preferred fix but meh
  code/modules/projectiles/boxes_magazines/internal/rifle.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
Labels: Bugfix [No Hold]

#700 Hotfixes for constructionlathe and whispering in crit/softcrit/hardcrit
  code/game/machinery/autolathe.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/say.dm
Labels: Bugfix [No Hold]

#698 Gives veteran legionary+ a machete gladius
  code/modules/jobs/job_types/legion.dm
Labels: Balance [24hr Hold], Feature [24hr Hold]

#708 Update smg.dm
  code/modules/projectiles/projectile/bullets/smg.dm
Labels: Bugfix [No Hold]

#696 Admin Ranks / Config
  config/admin_ranks.txt
  config/config.txt
Labels: Administrative, Do Not Merge, Hold[Tea/Ren input needed]

#699 Adds Sierra Power armor and gives it to the NCR Captain
  code/modules/clothing/suits/armor.dm
  code/modules/jobs/job_types/ncr.dm
  icons/mob/suit.dmi
Labels: Balance [24hr Hold], Feature [24hr Hold]

#715 new radio sprites
  icons/obj/radio.dmi
Labels: Quality of Life, Sprites

#722 General spring cleaning, staff perms
  config/admin_ranks.txt
  config/admins.example.txt
Labels: Administrative, Map Edit [Will Break Others], No Hold [Ren or Tea Override], Quality of Life

#724 Double the wait, double the fun!
  code/__DEFINES/mobs.dm
Labels: Administrative

#723 Adds changelog to pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  pull_request_template.md
Labels: Administrative

#721 Shotgun Pellet Number Reduction (and some minor QoL changes)
  code/datums/traits/good.dm
  code/game/machinery/deployable.dm
  code/game/objects/items/candle.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/plasticflaps.dm
  code/game/objects/structures/tribal_torch.dm
  code/modules/Wasteland/Wasteland Flora/wastelandPlants.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/projectiles/ammunition/ballistic/shotgun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  icons/obj/candle.dmi
  sound/f13machines/engine_running1.ogg
  sound/f13machines/engine_running2.ogg
  sound/f13machines/engine_running3.ogg
  sound/f13machines/engine_start.ogg
  tgstation.dme
Labels: Balance [24hr Hold]

#732 reformats the changelog
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Bugfix [No Hold]
