Repository BadDeathclaw/TG-Claw, pull requests merged in 2019-02, with the labels that each got.

#463 Gives pushers more uniforms to pick from.
  code/modules/jobs/job_types/wasteland.dm
Labels: question

#522 Map Changes, Bugfixes
  _maps/map_files/BoxStation/BoxStation.dmm
  code/game/area/Space_Station_13_areas.dm
  icons/turf/f13areas.dmi
Labels: Do Not Merge, Work In Progress

#496 [Reopen] [UPDATE] Medical crafting
  code/game/objects/items/grenades/chem_grenade.dm
  code/modules/crafting/recipes.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/research/designs/autolathe_designs.dm
Labels: Work In Progress

#283 Super advanced technology
  code/__DEFINES/traits.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/autolathe.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/objs.dm
  code/modules/awaymissions/corpse.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/den.dm
  code/modules/jobs/job_types/enclave.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/jobs/job_types/vault.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/mob.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/rdconsole.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Balance/Rebalance, Ready for merge, Refractor, optimization

#416 Removes some designs from all_nodes.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Work In Progress

#546 Attempt numero uno on jobs and quirks not saving
  code/__DEFINES/jobs.dm
  code/__HELPERS/cmp.dm
  code/__HELPERS/unsorted.dm
  code/controllers/subsystem/processing/quirks.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/jobs/job_types/job.dm
Labels: Ready for merge, optimization

#551 Removes xenobio from BoS
  _maps/map_files/generic/CentCom.dmm
Labels: Map Edit, Ready for merge

#563 Fixes kitchen processors
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/food_and_drinks/kitchen_machinery/processor.dm
  code/modules/food_and_drinks/recipes/processor_recipes.dm
Labels: Ready for merge

#539 nerfs every single healing chemical into the ground bar a couple
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Do Not Merge, Work In Progress

#507 Adds molerats (Not sure if I did it right)
  code/modules/mob/living/simple_animal/hostile/wasteanimals.dm
Labels: Feature, Grammar/Reformatting

#569 removes space from instruments
  code/game/objects/items/devices/instruments.dm
Labels: Grammar/Reformatting

#512 Addition of the Cornu horn for Vexillarius.
  code/game/objects/items/devices/megaphone.dm
  code/modules/jobs/job_types/legion.dm
  icons/mob/inhands/equipment/horns_lefthand.dmi
  icons/mob/inhands/equipment/horns_righthand.dmi
  icons/obj/musician.dmi
Labels: Feature, Work In Progress

#552 Does the things that treetea wanted.
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/xenobiology/crossbreeding/burning.dm
  code/modules/research/xenobiology/crossbreeding/regenerative.dm
  code/modules/research/xenobiology/crossbreeding/reproductive.dm
  code/modules/research/xenobiology/crossbreeding/stabilized.dm
Labels: Work In Progress

#584 You can no longer move at permanent ephedrinespeed through creating oldschool nuka cola
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
Labels: Balance/Rebalance

#585 Nerfs several alcohols so that they are no longer incredibly lethal (bye neurotoxin)
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Balance/Rebalance

#590 Bigger text input box for Me/Emote on IC menu.
  code/modules/mob/living/emote.dm
  code/modules/mob/say.dm
Labels: Feature

#589 Removes magicarps
  code/modules/events/wizard/magicarp.dm
Labels: Removal

#588 Map improvements, advanced signaler, brahmin calf, cornu.ogg
  _maps/map_files/BoxStation/BoxStation.dmm
  code/game/objects/items/devices/megaphone.dm
  code/game/objects/items/devices/radio/electropack.dm
  code/modules/assembly/signaler.dm
  code/modules/crafting/recipes.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/research/designs/autolathe_designs.dm
  sound/items/cornu.ogg
Labels: Feature, Map Edit, Sound

#599 Restart vote passing, with admins on now autocalls the shuttle
  code/controllers/subsystem/vote.dm
Labels: Administation, Quality of Life

#600 Buffs coders, Give them the game panel
  code/modules/admin/admin_verbs.dm
Labels: Administation, Quality of Life

#613 Hotfixes advanced signaler
  code/modules/assembly/signaler.dm
Labels: Bugfix [No Hold]

#607 Create pull_request_template.md
  pull_request_template.md
Labels: Administrative

#608 Moves from SS13.dm Spawners to F13lootdrop.dm spawners
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/generic/CentCom.dmm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/effects/spawners/ss13.dm
  code/game/turfs/closed.dm
  code/modules/antagonists/brainwashing/brainwashing.dm
  tgstation.dme
Labels: Feature [24hr Hold]

#620 Moves technophreak trait to mind datums
  code/__DEFINES/traits.dm
  code/datums/mind.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/storage/book.dm
  code/game/objects/items/toys.dm
  code/game/objects/objs.dm
  code/game/objects/structures/musician.dm
  code/game/turfs/simulated/minerals.dm
  code/game/turfs/simulated/walls.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/enclave.dm
  code/modules/jobs/job_types/silicon.dm
  code/modules/jobs/job_types/vault.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/mob.dm
  code/modules/paperwork/contract.dm
  code/modules/paperwork/handlabeler.dm
  code/modules/research/rdconsole.dm
Labels: Bugfix [No Hold], Quality of Life

#612 Adds gun slowdown
  code/__DEFINES/combat.dm
  code/__DEFINES/status_effects.dm
  code/__DEFINES/traits.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/items.dm
  code/modules/mob/living/carbon/human/status_procs.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/status_procs.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/status_procs.dm
  code/modules/projectiles/gun.dm
Labels: Balance [24hr Hold], Complex [24hr Hold], Feature [24hr Hold], Quality of Life

#618 Improve lewdcode quality
  code/modules/mob/living/carbon/human/human.dm
  code/modules/surgery/gender_reassignment.dm
  interactions/lewd/_lewd.dm
  interactions/lewd/lewd_datums.dm
  interactions/lewd/lewd_interactions.dm
  interactions/lewd/lewd_species.dm
  interactions/lewd/objects.dm
Labels: Feature [24hr Hold], Work In Progress [DNM]

#614 Fixes shock collars
  _maps/RandomRuins/SpaceRuins/oldAIsat.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/f13 closets.dm
  code/modules/assembly/electropack.dm
  code/modules/assembly/shock_kit.dm
  code/modules/crafting/recipes.dm
  code/modules/research/designs/autolathe_designs.dm
  tgstation.dme
Labels: Bugfix [No Hold], Complex [24hr Hold], Map Edit [Will Break Others], Quality of Life

#619 Comeback : Ghouls!
  code/__DEFINES/is_helpers.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/ghoul.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  config/game_options.txt
  icons/mob/human_parts.dmi
  tgstation.dme
Labels: Work In Progress [DNM]

#625 Lewd hotfix
  code/modules/mob/living/carbon/human/human.dm
  interactions/lewd/_lewd.dm
Labels: Bugfix [No Hold]

#627 Readds missing Area
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Bugfix [No Hold]

#628 Update gun.dm
  code/modules/projectiles/gun.dm
Labels: Bugfix [No Hold]

#631 Make ghouls hostile to ghoul players
  code/modules/mob/living/carbon/human/species_types/ghoul.dm
Labels: Balance [24hr Hold]

#635 Organisms fix
  code/modules/mob/living/carbon/human/human.dm
Labels: Bugfix [No Hold]

#646 A more proper fix
  code/modules/assembly/electropack.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/enclave.dm
  code/modules/jobs/job_types/job.dm
  code/modules/jobs/job_types/vault.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Bugfix [No Hold]

#644 Mob Migration 2: Electric Fork Update Edition
  _maps/map_files/BoxStation/BoxStation.dmm
  code/modules/mob/living/simple_animal/corpse.dm
  code/modules/mob/living/simple_animal/hostile/raider.dm
Labels: Balance [24hr Hold], Map Edit [Will Break Others]

#647 ghoul hair
  code/modules/mob/living/carbon/human/species_types/ghoul.dm
Labels: Balance [24hr Hold], Feature [24hr Hold], Quality of Life

#602 Removes some additional bad slime reactions
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
Labels: Do Not Merge, Work In Progress [DNM]

#636 Ghoul sprites
  icons/mob/human_parts.dmi
Labels: Sprites

#645 Adds Throwing spear recipe and Head on pike recipe with Throwing spears.
  code/modules/crafting/recipes.dm
Labels: Feature [24hr Hold]

#650 Adding Bighorners sprites and code -Might need unfucking-
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  icons/mob/wastemobs.dmi
Labels: Feature [24hr Hold]

#660 Cleans up signal transfer code + lowers hours times + map edits
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/generic/CentCom.dmm
  code/modules/assembly/signaler.dm
  code/modules/crafting/recipes.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/vault.dm
Labels: Balance [24hr Hold], Feature [24hr Hold], Map Edit [Will Break Others]
